
config.yml 
           Hello world 
                  Screaming around: [gmright]
    [0-actions] configurations 
     _broken: (lines) fix { work 
.{_blue/sky
.{_mat 
    CI-actions(test)> gmright2.github.io-
config.yml 

     Actually stay active 
  Actions : 0
Build: 0
PRC: 0
           _Buildlog 
           _buildlog/outperform 
  Action: 0.1
Build: 0.1
PRC: 0.1
      
 

      Maratani-build { hello world 
 Output: stand {> 
Input: tag> master 
 
                       Action: 1.0
                      Build: 1.0
                      PRC: 1.0
_slideshow reboot} outlook 
_slideshow mpn} outfit/ Measure #[400]:zoom 
                                #[Normal]: zoom 
                                #[300]:zoom 

Action: arguments-start { gmrightjuu
Build: test_CI 

Test-1 


MIT License

Copyright (c) 2020 Gmright

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.



       
